name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.2.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e650e2fed2cf01a1d2b8579cdd857f1a23f4cefc6922607c168af252a0c70a6"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
