name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.2.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5309c7b42a4bffb933b4e84a33d8978bd5cc3343cf91c38b9aa74bd6c68160af"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
