name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.2.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f82a6a7d5564462d9e1d8df40abc1fa22038ab29c3a99431b19fbd4fac2d72f2"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
