name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df69f961ec982537f2e8c7ab544ddeba7066b64b6e1ad8233aee4e4e66c5fb8a"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
