name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ae3dcc62dd9188dc4852da2b443a4f8b41075098a99e203d91e80769046e705"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
