name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.2.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6960ce9162937e5dea4a8a398126721725ac74dbc6cf1daca49ac79cf93f8415"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
