name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96747fa2200ec1176b195b6bd3621635c3b327300c1a12837306fb8f0fa9a015"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
