name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.0.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2c2a9decadad7f5d10fc3b894ef5025fe481ad857aa0295a15be0118fb4060b"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
