name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50620cfff640ce160b13602606e4daa6f89fa1d20ccd737669745fda895a075b"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
