name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df1ce8cf0e57c9338fcb557ccdb9680a5c85d893d7e520f65b93843bb2ef8012"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
