name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.2.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e2eacf5872e47cbc950482fa51e520fea77a9c3a57f575caa6af5beb2483c6c"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
