name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.2.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb106867a1570c9ed65dca50ed7661a22cbad536883ce7bdbf5f274fbaef18bf"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
