name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72869a6f6b77fb4609016ba042bc4236ac22431d43bdb5425e5d9809961eec38"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
