name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.0.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84f7dcd49978acc638e068df7d098f33254d4bb27ad90e220bb280d75f62d58d"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
