name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.1.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "379fd5674bf5aaa1f550716296c8f3512f8ccf03fb0b9739db9eda904823c04f"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
