name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.1.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58ddfa833085927476033382e52f333e06e938ac4b56f540b7ee929899ec0a36"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
