name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.0.1"

[index]
file = "index.toml"
hash-format = "md5"
hash = "a793409a96d2ef83bbee809ba5aa3a4c"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
