name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.0.1"

[index]
file = "index.toml"
hash-format = "md5"
hash = "39f444cfb98ea609c6c8e67ff4e41b87"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
