name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.2.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea15da2ddd42f737adfad1c79860d1716f87097cd5c25392af7bb287962bd5f6"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
