name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.2.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74ef8d6807fb9f2a3625e808129d122faccc996e896d9f161e58a88a45a450de"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
