name = "Artifacts (Fabric)"
filename = "artifacts-3.2.0+fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3269/478/artifacts-3.2.0+fabric.jar"
hash-format = "murmur2"
hash = "2913425933"

[update]
[update.curseforge]
file-id = 3269478
project-id = 401236
release-channel = "beta"
