name = "Bee Angry-est"
filename = "BeeAngryest-1.6.0+1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3111/425/BeeAngryest-1.6.0+1.16.3.jar"
hash-format = "murmur2"
hash = "3782031519"

[update]
[update.curseforge]
file-id = 3111425
project-id = 352296
release-channel = "beta"
