name = "Bewitchment"
filename = "bewitchment-1.16.5-8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3245/862/bewitchment-1.16.5-8.jar"
hash-format = "murmur2"
hash = "3194074288"

[update]
[update.curseforge]
file-id = 3245862
project-id = 394915
release-channel = "beta"
