name = "Biome Makeover"
filename = "biome-makeover-1.16.5-1.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3275/517/biome-makeover-1.16.5-1.3.4.jar"
hash-format = "murmur2"
hash = "2210369833"

[update]
[update.curseforge]
file-id = 3275517
project-id = 412182
release-channel = "beta"
