name = "Cardinal Components"
filename = "Cardinal-Components-API-2.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3270/712/Cardinal-Components-API-2.8.0.jar"
hash-format = "murmur2"
hash = "2443485508"

[update]
[update.curseforge]
file-id = 3270712
project-id = 318449
release-channel = "beta"
