name = "CraftPresence"
filename = "CraftPresence-Fabric-1.16.5-Release-1.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3266/601/CraftPresence-Fabric-1.16.5-Release-1.8.0.jar"
hash-format = "murmur2"
hash = "1036782497"

[update]
[update.curseforge]
file-id = 3266601
project-id = 297038
release-channel = "beta"
