name = "Draylar's Battle Towers"
filename = "battletowers-3.3.4-1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3248/247/battletowers-3.3.4-1.16.4.jar"
hash-format = "murmur2"
hash = "846538733"

[update]
[update.curseforge]
file-id = 3248247
project-id = 315386
release-channel = "beta"
