name = "Gate of Babylon"
filename = "gate-of-babylon-1.4.2-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3252/504/gate-of-babylon-1.4.2-1.16.5.jar"
hash-format = "murmur2"
hash = "3672236991"

[update]
[update.curseforge]
file-id = 3252504
project-id = 407500
release-channel = "beta"
