name = "Get Off My Lawn"
filename = "get-off-my-lawn-1.16.5-1.3.4-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3266/839/get-off-my-lawn-1.16.5-1.3.4-beta.jar"
hash-format = "murmur2"
hash = "1682716977"

[update]
[update.curseforge]
file-id = 3266839
project-id = 365750
release-channel = "beta"
