name = "Give Me Hats! [FABRIC]"
filename = "give-me-hats-1.16-1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3264/214/give-me-hats-1.16-1.5.jar"
hash-format = "murmur2"
hash = "330431373"

[update]
[update.curseforge]
file-id = 3264214
project-id = 384009
release-channel = "beta"
