name = "Gunpowder SleepVote"
filename = "gunpowder-sleepvote-1.0.3+gunpowder.0.3.1.mc.1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3139/474/gunpowder-sleepvote-1.0.3+gunpowder.0.3.1.mc.1.16.4.jar"
hash-format = "murmur2"
hash = "614952023"

[update]
[update.curseforge]
file-id = 3139474
project-id = 355570
release-channel = "beta"
