name = "Gunpowder Teleport"
filename = "gunpowder-teleport-1.0.5+gunpowder.0.4.3.mc.1.16.5.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3284/808/gunpowder-teleport-1.0.5+gunpowder.0.4.3.mc.1.16.5.jar"
hash-format = "murmur2"
hash = "3733737613"

[update]
[update.curseforge]
file-id = 3284808
project-id = 402042
release-channel = "beta"
