name = "Gunpowder Teleport"
filename = "gunpowder-teleport-1.0.4+gunpowder.0.4.1.mc.1.16.5.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3279/399/gunpowder-teleport-1.0.4+gunpowder.0.4.1.mc.1.16.5.jar"
hash-format = "murmur2"
hash = "2743983469"

[update]
[update.curseforge]
file-id = 3279399
project-id = 402042
release-channel = "beta"
