name = "Gunpowder"
filename = "gunpowder-base-0.4.0+patch.1+1.16.5.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3279/206/gunpowder-base-0.4.0+patch.1+1.16.5.jar"
hash-format = "murmur2"
hash = "1232477544"

[update]
[update.curseforge]
file-id = 3279206
project-id = 350123
release-channel = "beta"
