name = "Gunpowder Signshop"
filename = "gunpowder-signshop-1.0.0+gunpowder.0.3.4.mc.1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3142/666/gunpowder-signshop-1.0.0+gunpowder.0.3.4.mc.1.16.4.jar"
hash-format = "murmur2"
hash = "3373902564"

[update]
[update.curseforge]
file-id = 3142666
project-id = 429147
release-channel = "beta"
