name = "Gunpowder"
filename = "gunpowder-base-0.4.2+1.16.5.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3280/455/gunpowder-base-0.4.2+1.16.5.jar"
hash-format = "murmur2"
hash = "3736484200"

[update]
[update.curseforge]
file-id = 3280455
project-id = 350123
release-channel = "beta"
