name = "Gunpowder"
filename = "gunpowder-base-0.4.3+1.16.5.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3282/431/gunpowder-base-0.4.3+1.16.5.jar"
hash-format = "murmur2"
hash = "2288717122"

[update]
[update.curseforge]
file-id = 3282431
project-id = 350123
release-channel = "beta"
