name = "Inventory Sorting"
filename = "InventorySorter-1.7.9-1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3280/11/InventorySorter-1.7.9-1.16.jar"
hash-format = "murmur2"
hash = "995422031"

[update]
[update.curseforge]
file-id = 3280011
project-id = 325471
release-channel = "beta"
