name = "[Fabric] Enderporter"
filename = "enderporter-1.16.5-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3222/164/enderporter-1.16.5-1.0.2.jar"
hash-format = "murmur2"
hash = "1927066291"

[update]
[update.curseforge]
file-id = 3222164
project-id = 441763
release-channel = "beta"
