name = "Library of Exile"
filename = "Library-Of-Exile-1.16.5-1.0.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3240/209/Library-Of-Exile-1.16.5-1.0.8.jar"
hash-format = "murmur2"
hash = "2241548694"

[update]
[update.curseforge]
file-id = 3240209
project-id = 398780
release-channel = "beta"
