name = "Lifts"
filename = "lifts-1.16.5-1.0.5-BETA.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3244/221/lifts-1.16.5-1.0.5-BETA.jar"
hash-format = "murmur2"
hash = "685688451"

[update]
[update.curseforge]
file-id = 3244221
project-id = 451554
release-channel = "beta"
