name = "Mo' Colors"
filename = "mocolors-1.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3272/633/mocolors-1.1.2.jar"
hash-format = "murmur2"
hash = "3364087652"

[update]
[update.curseforge]
file-id = 3272633
project-id = 446767
release-channel = "beta"
