name = "Repurposed Structures (Fabric)"
filename = "repurposed_structures-1.16.5-1.10.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3264/249/repurposed_structures-1.16.5-1.10.1-fabric.jar"
hash-format = "murmur2"
hash = "653603864"

[update]
[update.curseforge]
file-id = 3264249
project-id = 391366
release-channel = "beta"
