name = "through-the-looking-glass"
filename = "TTLG-ALPHA.13.jar"
side = "both"

[download]
url = "https://github.com/Archydra-Studios/Through-the-Looking-Glass/releases/download/2.0.0-alpha.13/TTLG-ALPHA.13.jar"
hash-format = "sha256"
hash = "fe2ebb60cc5933dc40398e72dbb3c7d294825f946e216ee3dab1e413b7ea5092"
