name = "Tiny Trash Can"
filename = "ttc-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3197/572/ttc-1.2.0.jar"
hash-format = "murmur2"
hash = "196681451"

[update]
[update.curseforge]
file-id = 3197572
project-id = 442850
release-channel = "beta"
