name = "UnderFabric"
filename = "underfabric-1.2.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/UXm0RHnT/versions/1.2.1/underfabric-1.2.2.jar"
hash-format = "sha512"
hash = "a2d0e7f1520e2cc75a94cb8028fb668b635b15946cad1d2aeddcbfe681a0400c00e6023f4516c0bca6d6bead9130d090dd23f1183d33d5086a4845addd166cdd"

[update]
[update.modrinth]
mod-id = "UXm0RHnT"
version = "W36MkxmB"
