name = "Wireless Networks"
filename = "wirelessnetworks-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3282/51/wirelessnetworks-1.0.2.jar"
hash-format = "murmur2"
hash = "1778435509"

[update]
[update.curseforge]
file-id = 3282051
project-id = 461316
release-channel = "beta"
