name = "World Border Fix"
filename = "worldborderfix-1.1-fabric-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3240/350/worldborderfix-1.1-fabric-1.16.5.jar"
hash-format = "murmur2"
hash = "421376113"

[update]
[update.curseforge]
file-id = 3240350
project-id = 443120
release-channel = "beta"
